# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CsvCreatorDialog
                                 A QGIS plugin
 This plugin creates csv files using shape file
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-14
        git sha              : $Format:%H$
        copyright            : (C) 2026 by mjkim
        email                : minji7658@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtCore import QVariant
from PyQt5.QtWidgets import QDialogButtonBox
from qgis.core import (
    QgsVectorLayer,
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsPointXY,
    QgsProject
)
import csv

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'csv_creator_dialog_base.ui'))

class CsvCreatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(CsvCreatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.label_count.setText("")
        self.pushButton_shp.clicked.connect(self.load_shp)
        self.ok_button = self.button_box.button(QDialogButtonBox.Ok)
        self.ok_button.clicked.connect(self.create_csv)

    def load_shp(self):
        print("import SHP 버튼 클릭")
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "SHP 파일 선택",
            "C:/Users/user/Desktop/kmj/2026.05/0514 (T)/QGIS 플러그인 개발/data",
            "Shape Files (*.shp)"
        )

        if file_path:
            self.lineEdit_shp.setText(file_path)
            try:
                layer = QgsVectorLayer(file_path, "tactile_blocks", "ogr") # ogr : shapefile 읽는 드라이버
                if not layer.isValid():
                    print("레이어 읽기 실패")
                else:
                    print("레이어 읽기 성공")

                    # featureCount() : 데이터 개수
                    count = layer.featureCount() 
                    print(f"데이터 개수: {count}")
                    self.label_count.setText(f"data count: {count}")
            except Exception as e:
                print(f"파일 읽기 오류: {e}")

    def create_csv(self):
        csv_path, _ = QFileDialog.getSaveFileName(
            self,
            "CSV 저장",
            "",
            "CSV Files (*.csv)"
        )

        if csv_path:
            file_path = self.lineEdit_shp.text()
            layer = QgsVectorLayer(file_path, "tactile_blocks", "ogr") # ogr : shapefile 읽는 드라이버

            with open(csv_path, mode="w", newline="", encoding="utf-8-sig") as file:
                writer = csv.writer(file)

                # 헤더
                writer.writerow([
                    "block_id",
                    "type",
                    "x1", "y1",
                    "x2", "y2",
                    "x3", "y3",
                    "x4", "y4",
                    "center_x",
                    "center_y"
                ])

                for feature in layer.getFeatures():
                    geom = feature.geometry()
                    multipolygon = geom.asMultiPolygon()
                    points = multipolygon[0][0]

                    # 중심점 계산
                    centroid = geom.centroid()
                    center_point = centroid.asPoint()

                    center_x = round(center_point.x(), 6)
                    center_y = round(center_point.y(), 6)

                    block_id = feature["block_id"]
                    ty = feature["type"]
                    x1 = points[0].x()
                    y1 = points[0].y()
                    x2 = points[3].x()
                    y2 = points[3].y()
                    x3 = points[2].x()
                    y3 = points[2].y()
                    x4 = points[1].x()
                    y4 = points[1].y()

                    writer.writerow([
                        block_id,
                        ty,
                        x1, y1,
                        x2, y2,
                        x3, y3,
                        x4, y4,
                        center_x, 
                        center_y
                    ])
            print("CSV 저장 완료")