# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PointMakerDialog
                                 A QGIS plugin
 This plugin creates points using coordinate values
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-11
        git sha              : $Format:%H$
        copyright            : (C) 2026 by mjkim
        email                : minji7658@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QFileDialog

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'point_maker_dialog_base.ui'))


class PointMakerDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PointMakerDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_csv.clicked.connect(self.load_csv)
    
    def load_csv(self):
        print("import CSV 버튼 클릭")
        file_path, _ = QFileDialog.getOpenFileName( # QFileDialog.getOpenFileName : 파일 탐색기 열기
            self,
            "CSV 파일 선택", # 창 제목
            "", # 초기 폴더 위치(비워둘 경우 기본 위치)
            "CSV Files (*.csv)" # csv 파일만 보이게 필터링
        )

        if file_path:
            self.lineEdit_csv.setText(file_path)