# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonEvaluatorDialog
                                 A QGIS plugin
 This plugin evaluate polygon matching accuracy between two shapefiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by mjkim
        email                : minji7658@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QDialogButtonBox
from qgis.core import (
    QgsVectorLayer,
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsPointXY,
    QgsProject
)
import csv

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'polygon_evaluator_dialog_base.ui'))


class PolygonEvaluatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PolygonEvaluatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_gt.clicked.connect(self.load_gt)
        self.pushButton_pred.clicked.connect(self.load_pred)


    def load_gt(self):
        print("import GT 버튼 클릭")
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "GT 파일 선택",
            "C:/Users/user/Desktop/kmj/2026.05/0518 (M)/QGIS 플러그인 개발/data/shp/5186",
            "Shape Files (*.shp)"
        )

        if file_path:
            self.lineEdit_gt.setText(file_path)
            try:
                layer = QgsVectorLayer(file_path, "tactile_blocks_gt", "ogr")
                if not layer.isValid():
                    print("GT 레이어 읽기 실패")
                else:
                    print("GT 레이어 읽기 성공")

                    # GT 데이터 카운트 확인
                    count = layer.featureCount()
                    print(f"GT 데이터 개수: {count}")
                    self.label_gtCount.setText(f"GT count: {count}")
            except Exception as e:
                print(f"GT 파일 읽기 오류: {e}")

    def load_pred(self):
        print("import Pred 버튼 클릭")
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Pred 파일 선택",
            "C:/Users/user/Desktop/kmj/2026.05/0518 (M)/QGIS 플러그인 개발/data/shp/5186",
            "Shape Files (*.shp)"
        )

        if file_path:
            self.lineEdit_pred.setText(file_path)
            try:
                layer = QgsVectorLayer(file_path, "tactile_blocks_pred", "ogr")
                if not layer.isValid():
                    print("Pred 레이어 읽기 실패")
                else:
                    print("Pred 레이어 읽기 성공")

                    # Pred 데이터 카운트 확인
                    count = layer.featureCount()
                    print(f"Pred 데이터 개수: {count}")
                    self.label_predCount.setText(f"Pred count: {count}")
            except Exception as e:
                print(f"Pred 파일 읽기 오류: {e}")
    
