# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PolygonEvaluatorDialog
                                 A QGIS plugin
 This plugin evaluate polygon matching accuracy between two shapefiles
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-05-18
        git sha              : $Format:%H$
        copyright            : (C) 2026 by mjkim
        email                : minji7658@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtWidgets import QDialogButtonBox
from qgis.core import (
    QgsVectorLayer,
    QgsFeature,
    QgsField,
    QgsGeometry,
    QgsPointXY,
    QgsProject
)
import csv

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'polygon_evaluator_dialog_base.ui'))


class PolygonEvaluatorDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(PolygonEvaluatorDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.label_thresholdText.setText("")
        self.pushButton_gt.clicked.connect(self.load_gt)
        self.pushButton_pred.clicked.connect(self.load_pred)
        self.ok_button = self.button_box.button(QDialogButtonBox.Ok)
        self.button_box.accepted.disconnect() # 기본 dialog 종료 기능 제거
        self.ok_button.clicked.connect(self.evaluate_polygon)
        self.doubleSpinBox.valueChanged.connect(self.check_threshold) # IoU 값 바뀔때마다 실행

    def load_gt(self):
        print("import GT 버튼 클릭")
        # 파일 탐색기 열기
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "GT 파일 선택",
            "C:/Users/user/Desktop/kmj/2026.05/0520 (W)/QGIS 플러그인 개발/data/GT",
            "Shape Files (*.shp)"
        )

        if file_path:
            self.lineEdit_gt.setText(file_path)
            try:
                # 레이어 이름: gt, ogr: GDAL 라이브러리의 벡터 데이터 읽기 엔진(shapefile 읽는 드라이버)
                layer = QgsVectorLayer(file_path, "gt", "ogr")
                if not layer.isValid():
                    print("GT 레이어 읽기 실패")
                else:
                    print("GT 레이어 읽기 성공")

                    # GT 데이터 카운트 확인
                    count = layer.featureCount()
                    print(f"GT 데이터 개수: {count}")
                    self.label_gtCount.setText(f"GT count: {count}")
            except Exception as e:
                print(f"GT 파일 읽기 오류: {e}")

    def load_pred(self):
        print("import Pred 버튼 클릭")
        file_path, _ = QFileDialog.getOpenFileName(
            self,
            "Pred 파일 선택",
            "C:/Users/user/Desktop/kmj/2026.05/0520 (W)/QGIS 플러그인 개발/data/Pred",
            "Shape Files (*.shp)"
        )

        if file_path:
            self.lineEdit_pred.setText(file_path)
            try:
                layer = QgsVectorLayer(file_path, "pred", "ogr")
                if not layer.isValid():
                    print("Pred 레이어 읽기 실패")
                else:
                    print("Pred 레이어 읽기 성공")

                    # Pred 데이터 카운트 확인
                    count = layer.featureCount()
                    print(f"Pred 데이터 개수: {count}")
                    self.label_predCount.setText(f"Pred count: {count}")
            except Exception as e:
                print(f"Pred 파일 읽기 오류: {e}")
    
    def evaluate_polygon(self):
        file_pathGt = self.lineEdit_gt.text()
        file_pathPred = self.lineEdit_pred.text()

        if not os.path.exists(file_pathGt) or not os.path.exists(file_pathPred):
            print("파일 경로가 올바르지 않습니다.")
            return
        
        # 0. Shape 파일 읽어서 벡터 레이어 객체 생성
        gt_layer = QgsVectorLayer(file_pathGt, "gt", "ogr")
        pred_layer = QgsVectorLayer(file_pathPred, "pred", "ogr")

        if not gt_layer.isValid() or not pred_layer.isValid():
            print("레이어 로드 실패")
            return

        # 1. 좌표계 동일한지 확인
        if gt_layer.crs() != pred_layer.crs():
            print(f"GT crs: {gt_layer.crs()}, Pred crs: {pred_layer.crs()}" )
            print("좌표계가 다릅니다.")
            return

        # 2. IoU Threshold 값 가져오기
        iou_threshold = self.doubleSpinBox.value()
        print(f"IoU Threshold: {iou_threshold}")

        # 3. Feature 리스트 만들기
        gt_features = list(gt_layer.getFeatures())
        pred_features = list(pred_layer.getFeatures())

        # 4. matching 관리
        # 하나의 GT Polygon이 여러 Pred와 중복 TP되면 안 됨
        # 따라서 중복 불가능한 set 사용
        matched_gt = set()
        matched_pred = set() # GT와 성공적으로 매칭된 Pred polygon들

        # 5. polygon matching
        # 각 GT polygon마다 가장 많이 겹치는 Pred polygon 찾기
        tp = 0
        result_rows = []

        # 각 GT polygon마다 가장 IoU가 높은 Pred polygon 하나를 찾고, Threshold 이상이면서 type이 같으면 TP로 인정
        for gt_idx, gt_feat in enumerate(gt_features): # GT 하나씩 꺼내기
            gt_geom = gt_feat.geometry()

            best_iou = 0 # 가장 높은 IoU 저장
            best_pred_idx = -1
            
            # 모든 Pred와 비교 
            for pred_idx, pred_feat in enumerate(pred_features):
                # 이미 사용된 Pred는 건너뜀
                if pred_idx in matched_pred:
                    continue
                
                pred_geom = pred_feat.geometry()

                # type 가져오기
                gt_type = str(gt_feat["Shape_Type"]).lower()
                pred_type = str(pred_feat["type"]).lower()

                # type 다르면 skip
                if gt_type != pred_type:
                    continue

                # IoU 계산
                iou = self.calculate_iou(gt_geom, pred_geom)

                if iou > best_iou:
                    best_iou = iou
                    best_pred_idx = pred_idx
            
            if best_iou >= iou_threshold:
                tp += 1

                matched_gt.add(gt_idx)
                matched_pred.add(best_pred_idx)

                gt_points = self.extract_polygon_points(gt_geom) # 폴리곤 좌표 추출

                pred_geom = pred_features[best_pred_idx].geometry()
                pred_points = self.extract_polygon_points(pred_geom)

                # if len(gt_points) != len(pred_points):
                #     continue

                # 좌표 오차 계산
                errors = self.calculate_coordinate_errors(
                    gt_points,
                    pred_points
                )

                # 면적 계산
                gt_area = gt_geom.area()
                pred_area = pred_geom.area()

                # symDifference: 겹치지 않는 부분만 남김
                error_geom = gt_geom.symDifference(pred_geom) 
                error_area = error_geom.area()

                # csv 저장용 데이터
                result_rows.append({
                    "gt_points": gt_points,
                    "gt_area": gt_area,

                    "pred_points": pred_points,
                    "pred_area": pred_area,

                    "errors": errors,
                    "error_area": error_area
                })

        # FP / FN 계산 
        fp = len(pred_features) - len(matched_pred) # 전체 Pred 개수 - 매칭 성공한 Pred 개수
        fn = len(gt_features) - len(matched_gt) # 전체 GT 개수 - 매칭 성공한 GT 개수 = 미탐

        # Precision / Recall / F1 Score 계산
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1_score = (
            2 * precision * recall / (precision + recall)
            if (precision + recall) > 0 else 0
        )

        # 결과 출력
        print(f"TP: {tp}")
        print(f"FP: {fp}")
        print(f"FN: {fn}")

        print(f"Precision: {precision:.4f}")
        print(f"Recall: {recall:.4f}")
        print(f"F1 Score: {f1_score:.4f}")

        self.label_precision.setText(f"Precision: {precision:.4f}")
        self.label_recall.setText(f"Recall: {recall:.4f}")
        self.label_f1Score.setText(f"F1 Score: {f1_score:.4f}")

        # 결과를 csv 파일로 저장
        self.create_csv(tp, fp, fn, precision, recall, f1_score, result_rows)

    # IoU 계산 함수
    def calculate_iou(self, geom1, geom2):
        # 실제 겹치는 부분 계산
        # 여기서 intersection은 겹치는 polygon geometry(객체)
        intersection = geom1.intersection(geom2)

        if intersection.isEmpty():
            return 0.0

        # 겹치는 polygon의 실제 면적 계산 
        intersection_area = intersection.area()

        # GT polygon과 Pred polygon의 각 면적 계산
        area1 = geom1.area()
        area2 = geom2.area()

        # 두 polygon의 겹치는 부분 빼줌
        union_area = area1 + area2 - intersection_area

        if union_area == 0:
            return 0.0

        iou = intersection_area / union_area

        return iou

    # csv 파일 생성 함수
    def create_csv(self, tp, fp, fn, precision, recall, f1_score, result_rows):
        csv_path, _ = QFileDialog.getSaveFileName(
            self,
            "CSV 저장",
            "C:/Users/user/Desktop/kmj/2026.05/0520 (W)/QGIS 플러그인 개발/result",
            "CSV Files (*.csv)"
        )

        if csv_path:
            with open(csv_path, mode="w", newline="", encoding="utf-8-sig") as file:
                writer = csv.writer(file)

                # 헤더
                writer.writerow([
                    "input(GT)",
                    "GT area",

                    "reference(Pred)",
                    "Pred area",

                    "error",
                    "Error area",

                    "", 
                    "tp",
                    "fp",
                    "fn",

                    "precision",
                    "recall",
                    "f1_score"
                ])

                for idx, row in enumerate(result_rows):
                    # 첫 번째 row에만 metric 저장
                    if idx == 0:
                        metric_tp = tp
                        metric_fp = fp
                        metric_fn = fn

                        metric_precision = round(precision, 3)
                        metric_recall = round(recall, 3)
                        metric_f1 = round(f1_score, 3)

                    # 나머지 row는 빈칸
                    else:
                        metric_tp = ""
                        metric_fp = ""
                        metric_fn = ""

                        metric_precision = ""
                        metric_recall = ""
                        metric_f1 = ""
                        
                    writer.writerow([
                        [(round(x, 3), round(y, 3))
                        for x, y in row["gt_points"]],
                        round(row["gt_area"], 3), 

                        [(round(x, 3), round(y, 3))
                        for x, y in row["pred_points"]],
                        round(row["pred_area"], 3),

                        [(round(x, 3), round(y, 3))
                        for x, y in row["errors"]],
                        round(row["error_area"], 3), 

                        "",
                        metric_tp,
                        metric_fp,
                        metric_fn,

                        metric_precision,
                        metric_recall,
                        metric_f1
                    ])
                
            print("csv 저장 완료")

    def check_threshold(self):
        iou_threshold = self.doubleSpinBox.value()

        if iou_threshold <= 0:
            self.ok_button.setEnabled(False)
            self.label_thresholdText.setText("IoU Threshold 값은 0보다 커야 합니다.")
            self.label_thresholdText.setStyleSheet("color: red;")
            print("IoU Threshold 값은 0보다 커야함")
        else:
            self.ok_button.setEnabled(True)
            self.label_thresholdText.setText("")

    # polygon 좌표 추출 함수
    # QGIS polygon 구조는 아래와 같음
    # Polygon
    #   ㄴ Ring(외곽선)
    #       ㄴ Points(0,0)
    #       ㄴ Points(10,0)
    #       ㄴ Points(10,10)
    #       ㄴ Points(0,10)
    #       ㄴ Points(0,0) <-- 시작점 반복
    def extract_polygon_points(self, geom):
        points = []

        # 일반 polygon
        if geom.isMultipart() == False:
            polygon = geom.asPolygon()

            if not polygon:
                return []

            # polygon[0]은 첫 번째 ring을 꺼내는 것임
            # [
            #    [ Point(0,0),
            #      Point(10,0),
            #      Point(10,10),
            #      Point(0,10),
            #      Point(0,0)
            #    ]
            # ]
            ring = polygon[0]

            for pt in ring[:-1]: # 마지막 점이 시작점 반복하기 때문에 마지막 점 제외하기 위해서 -1
                points.append((pt.x(), pt.y()))
        else:
            # MultiPolygon 구조
            # QGIS polygon 구조는 아래와 같음
            # MultiPolygon
            # ㄴ Polygon
            #    ㄴ Ring(외곽선)
            #       ㄴ Points
            # [
            #    [
            #       [ Point(0,0),
            #         Point(10,0),
            #         Point(10,10),
            #         Point(0,10),
            #         Point(0,0)
            #       ]
            #    ]
            # ]
            multipolygon = geom.asMultiPolygon()

            if not multipolygon:
                return []

            # 첫 번째 polygon만 사용
            ring = multipolygon[0][0]

            for pt in ring[:-1]:
                points.append((pt.x(), pt.y()))
        
        return points

    # # Error 좌표 계산 함수
    # def calculate_coordinate_errors(self, gt_points, pred_points):
    #     errors = []

    #     # zip(): 두 리스트를 동시에 순회
    #     for gt_pt, pred_pt in zip(gt_points, pred_points):
    #         x_error = pred_pt[0] - gt_pt[0]
    #         y_error = pred_pt[1] - gt_pt[1]

    #         errors.append((x_error, y_error))

    #     return errors

    # Error 좌표 계산 함수
    # GT의 각 점마다 가장 가까운 Pred 점을 찾는 방식
    def calculate_coordinate_errors(self, gt_points, pred_points):
        errors = []

        # GT point 하나씩 순회
        for gt_pt in gt_points:

            min_distance = float("inf")
            nearest_pred_pt = None

            # 모든 Pred point와 거리 비교
            for pred_pt in pred_points:

                dx = pred_pt[0] - gt_pt[0]
                dy = pred_pt[1] - gt_pt[1]

                distance = (dx ** 2 + dy ** 2) ** 0.5

                # 가장 가까운 점 저장
                if distance < min_distance:
                    min_distance = distance
                    nearest_pred_pt = pred_pt

            # 가장 가까운 Pred 점과의 오차 계산
            x_error = nearest_pred_pt[0] - gt_pt[0]
            y_error = nearest_pred_pt[1] - gt_pt[1]

            errors.append((x_error, y_error))

        return errors